= Deploying Jupyter Lab on an AWS EC2 Instance
:stylesheet: boot-darkly.css
:linkcss: boot-darkly.css
:image-url-ironhack: https://github.com/jecastrom/jupyter_lab_on_aws_ec2/blob/main/img/banner%20jupyter%20deploy.png
:my-name: Jorge Castro
:description:
:script-url: https://github.com/jecastrom/data_2.07_activities/blob/7abfb6a0375c2c4ad3021f3f9a388a495142e1a8/files_for_actitity/act%202.07%20solutions.sql
//:fn-xxx: Add the explanation foot note here bla bla
:toc:
:toc-title: Step-by-Step Guide on how to deploy Jupyter Lab on an Ubuntu EC2 instance
:toc-placement!:
:toclevels: 5
ifdef::env-github[]
:sectnums:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:experimental:
:table-caption!:
:example-caption!:
:figure-caption!:
:idprefix:
:idseparator: -
:linkattrs:
:fontawesome-ref: http://fortawesome.github.io/Font-Awesome
:icon-inline: {user-ref}/#inline-icons
:icon-attribute: {user-ref}/#size-rotate-and-flip
:video-ref: {user-ref}/#video
:checklist-ref: {user-ref}/#checklists
:list-marker: {user-ref}/#custom-markers
:list-number: {user-ref}/#numbering-styles
:imagesdir-ref: {user-ref}/#imagesdir
:image-attributes: {user-ref}/#put-images-in-their-place
:toc-ref: {user-ref}/#table-of-contents
:para-ref: {user-ref}/#paragraph
:literal-ref: {user-ref}/#literal-text-and-blocks
:admon-ref: {user-ref}/#admonition
:bold-ref: {user-ref}/#bold-and-italic
:quote-ref: {user-ref}/#quotation-marks-and-apostrophes
:sub-ref: {user-ref}/#subscript-and-superscript
:mono-ref: {user-ref}/#monospace
:css-ref: {user-ref}/#custom-styling-with-attributes
:pass-ref: {user-ref}/#passthrough-macros
endif::[]
ifndef::env-github[]
:imagesdir: ./
endif::[]

image::{image-url-ironhack}[width=900]

{my-name}


                                                     
====
''''
====
toc::[]

{description}


== Steps to Provisioning the EC2 Instance

=== Creating the key pair

To be able to SSH to the instance we need to create a key pair and store it on a file.

```
aws ec2 create-key-pair \
--key-name jupyter_test-key \
--query "KeyMaterial" \
--output text > jupyter_test_key.pem
```

To change the permissions of the .pem file we just created:

```
chmod 400 jupyter_test_key.pem
```

=== Creating a new Security Group

To create a new security group, we need to find out first the vpc-id in our region. Instead of just making the query, we are going to save the result on a variable called `myvpc_id` and use it to create the security group

```
myvpc_id=$(aws ec2 describe-vpcs \
--query "Vpcs[].{vpcid:VpcId}" \
--output text)
```

Now we can create our new security group using the variable containing the vpc-id

```
aws ec2 create-security-group \
--group-name jupyter-sg \
--description "Jupyter Lab Instance" \
--vpc-id $myvpc_id
```



=== Provisioning the EC2

=== Connecting to the EC2 Instance via SSH

== Installing Jupyter Lab

=== Run Jupyter Lab in the backgrounds




====
''''
====



====
''''
====




xref:Lab-xxxx[Top Section]



//bla bla blafootnote:[{fn-xxx}]


////
.Unordered list title
* gagagagagaga
** gagagatrtrtrzezeze
*** zreu fhjdf hdrfj 
*** hfbvbbvtrtrttrhc
* rtez uezrue rjek  

.Ordered list title
. rwieuzr skjdhf
.. weurthg kjhfdsk skhjdgf
. djhfgsk skjdhfgs 
.. lksjhfgkls ljdfhgkd
... kjhfks sldfkjsdlk




[,sql]
----
----



[NOTE]
====
A sample note admonition.
====
 
TIP: It works!
 
IMPORTANT: Asciidoctor is awesome, don't forget!
 
CAUTION: Don't forget to add the `...-caption` document attributes in the header of the document on GitHub.
 
WARNING: You have no reason not to use Asciidoctor.

bla bla bla the 1NF or first normal form.footnote:[{1nf}]Then wen bla bla


====
- [*] checked
- [x] also checked
- [ ] not checked
-     normal list item
====
[horizontal]
CPU:: The brain of the computer.
Hard drive:: Permanent storage for operating system and/or user files.
RAM:: Temporarily stores information the CPU uses during operation.






bold *constrained* & **un**constrained

italic _constrained_ & __un__constrained

bold italic *_constrained_* & **__un__**constrained

monospace `constrained` & ``un``constrained

monospace bold `*constrained*` & ``**un**``constrained

monospace italic `_constrained_` & ``__un__``constrained

monospace bold italic `*_constrained_*` & ``**__un__**``constrained

////
